wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.12
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700068512.524749
    t:
      1:
      - 55
      - 105
      2:
      - 55
      - 105
      3:
      - 13
      - 23
      4: 3.11.5
      5: 0.15.12
      8:
      - 3
      - 5
      13: windows-amd64
